# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    scan(
      scheme: "HOMEY Clean",
      project: "../HOMEY Clean.xcodeproj",
      skip_build: false,
      build_for_testing: true
    )
  end

  desc "Build for development"
  lane :build do
    build_app(
      scheme: "HOMEY Clean",
      project: "../HOMEY Clean.xcodeproj",
      export_method: "development"
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    # Load App Store Connect API key from JSON file
    api_key_path = "fastlane/asc_api_key.json"
    if File.exist?(api_key_path)
      api_key_json = JSON.parse(File.read(api_key_path))
      api_key = app_store_connect_api_key(
        key_id: api_key_json["key_id"],
        issuer_id: api_key_json["issuer_id"],
        key_content: api_key_json["key"],
        in_house: api_key_json["in_house"]
      )
    end
    
    build_app(
      scheme: "HOMEY Clean",
      project: "../HOMEY Clean.xcodeproj",
      export_method: "app-store"
    )
    
    upload_to_testflight(
      api_key: api_key_json ? api_key : nil,
      skip_waiting_for_build_processing: true
    )
  end
end